# ~/.config/starship.toml

[username]
style_root = "magenta bold"
style_user = "green bold"
format = "[$user]($style)"
show_always = true

[hostname]
format = "[@$hostname](bold green) "
ssh_only = false
