# ~/.config/starship.toml

[username]
format = "[$user](white)"
show_always = true

[hostname]
format = "[@$hostname](bold green) ï£¿ "
ssh_only = false

[memory_usage]
style = "dimmed"
disabled = false
threshold = -1
format = "[${ram}]($style) "
